In [50]:
import numpy as np
import pandas as pd

In [3]:
df= pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
pd.__version__

'3.0.5'

In [8]:
df.shape[0]

10000

In [9]:
df.fuel_type.nunique()

3

In [11]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [12]:
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [26]:
median1 = df['horsepower'].median()
median1

np.float64(254.0)

In [32]:
mode = df['horsepower'].mode()[0]
mode

np.float64(252.0)

In [33]:
df['horsepower'] = df['horsepower'].fillna(mode)

In [ ]:
df['horsepower'].isnull().sum()  #check to see if there is any missing values

np.int64(0)

In [35]:
median2 = df['horsepower'].median()
median2

np.float64(252.0)

In [45]:
asia_cars = df[df['origin'] == 'Asia']

columns = asia_cars[['vehicle_weight', 'model_year']]

first_seven = columns.head(7)
first_seven

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [46]:
X = first_seven.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [57]:
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [61]:
invX = np.linalg.inv(XTX)
invX

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [59]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [62]:
w = invX.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [63]:
np.sum(w)

np.float64(0.36919696904925486)